### ISSUE TITLE
Need Team Access to view the frontend...?

### ISSUE THREAD

**Issue by wptechprodigy** [Chimise/bank-blockchain-app#41]
I need a Team Access to be able to view the deployed frontend.

I don't think this should be. 
Anyone with the link should be able to view the deployed frontend.

<img width="780" alt="Screenshot 2024-03-03 at 10 34 03" src="https://github.com/Chimise/bank-blockchain-app/assets/22558674/f12014a9-340c-4633-bb73-1f2b1ae8db0c">

@olaoluwasmith 
@Chimise 
@ibrahim-san 
@Mitrawsm

**Comment by lordlughas** [comment]
Access has been granted
